feat(playground): add global types
vexip-ui/vexip-ui pull request #397
Opened 2023-08-03 21:30 UTC by Sight-wcg

### Description

Add global types.

![image](https://github.com/vexip-ui/vexip-ui/assets/26325820/4e33497a-1329-4c72-b8a7-51e02b88055a)

### Linked Issues

### Additional Context

2023-08-04 07:24 UTC, qmhc requested changes

2023-08-04 07:24 UTC, qmhc commented on playground/templates/tsconfig.json
> +    "allowImportingTsExtensions": true,
这个应该是不必要的，是出于什么目的需要添加 `allowImportingTsExtensions` 呢？

2023-08-04 13:55 UTC, Sight-wcg commented on playground/templates/tsconfig.json
> +    "allowImportingTsExtensions": true,
@vue/repl 在以前的版本中导入 ts 文件必须包含 \` .ts \` 扩展名，这是 esm 模块规范强制要求的。repl 2.x 版本为了保证兼容性，预设的 \`tsconfig.json\` 开启了个选项。 [https://github.com/vuejs/repl/blob/main/src/store.ts#L31-L44](https://github.com/vuejs/repl/blob/main/src/store.ts#L31-L44)

更多信息参考 https://gist.github.com/andrewbranch/79f872a8b9f0507c9c5f2641cfb3efa6#module-resolution-for-bundlers-typescript-runtimes-and-node-loaders

2023-08-07 01:19 UTC, qmhc commented
在打包后，似乎类型并不会生效。

你可以尝试 `pnpm run build:playground` 然后 `pnpm -C playground preview` 查看打包后的预览效果。

2023-08-07 02:34 UTC, Sight-wcg commented
> 在打包后，似乎类型并不会生效。
> 
> 你可以尝试 `pnpm run build:playground` 然后 `pnpm -C playground preview` 查看打包后的预览效果。

我尝试清除 vite 缓存，浏览器缓存后按照上述步骤运行预览，没有发现问题。

*   系统 Windows 10
*   浏览器 Edge 115

![](https://github.com/vexip-ui/vexip-ui/assets/26325820/68251892-e660-4e97-a464-7b5c7077e8e9)

可能的原因

*   从 CDN 加载类型缓慢，初次需要等待一段时间
*   检查 repl 版本是否是最新版（v2.5.6）,[2.5.3~2.5.5 有一些 Bug 影响 vueWorker](https://github.com/vuejs/repl/compare/v2.5.2...v2.5.3#diff-6ae3ac3ac9366d4a93e5062881f137934d4b6725283363accf14ef8b8d4300aaL29)

2023-08-07 02:42 UTC, qmhc commented
好的，请你本地安装一次依赖以更新 lock 文件，并提交更新。当前的 ci 在 lock 文件中发现不同步。

2023-08-07 03:49 UTC, qmhc approved these changes

2023-08-07 03:50 UTC, merged